import type {Module} from './types';
const regions=['West','South','North'], months=['January','February','March','April','May','June','July','August','September','October','November','December'];
const f=(name:string,type:any='text',options?:string[],_required=false,section='Details')=>({name,type,options,required:false,section,label:name.startsWith('NN/EC')?'New Opportunity / Existing Customer':undefined});
export const modules:Module[]=[
{id:'weekly-review',label:'Weekly Review',description:'Capture opportunity progress and weekly updates.',status:true,fields:[f('Region','select',regions,true,'Customer & ownership'),f('AM','text',undefined,false,'Customer & ownership'),f('Presales','text',undefined,true,'Customer & ownership'),f('Customer','text',undefined,true,'Customer & ownership'),f('Date of Opportunity (MM/YY)','month',undefined,false,'Opportunity'),f('Opportunity Details','textarea',undefined,true,'Opportunity'),f('NN/EC (New Opportunity/Existing Customer)','select',['New Opportunity','Existing Customer'],false,'Opportunity'),f('Value (₹)','number',undefined,false,'Commercial / Forecast'),f('OEM','text',undefined,false,'Commercial / Forecast'),f('Stage','select',['Funnel','Upside','Commit','Win','Lost'],false,'Commercial / Forecast'),f('Expected Closure (QTR)','select',['Q1','Q2','Q3','Q4'],false,'Commercial / Forecast'),f('Month','select',months,false,'Commercial / Forecast'),f('Remarks','textarea',undefined,false,'Weekly updates'),...['Week 1','Week 2','Week 3','Week 4'].map(x=>f(x,'textarea',undefined,false,'Weekly updates'))]},
{id:'weekly-meeting',label:'Weekly Meetings',description:'Log customer meetings, decisions, and follow-ups.',status:true,fields:[f('Region','select',regions,true),f('Month','select',months),f('Week','select',['1','2','3','4','5']),f('Date','date',undefined,true),f('Presales','text',undefined,true),f('Client Manager'),f('Account Name','text',undefined,true),f('Account Type(New/Existing)','select',['New','Existing']),f('Meeting Mode (In-Person/Virtual)','select',['In-Person','Virtual']),f('Meeting Agenda','textarea',undefined,true),f('Discussion Points','textarea'),f('Action Items','textarea'),f('Remarks','textarea')]},
{id:'training-attended',label:'Training Attended',description:'Record learning and certification activity.',status:true,fields:[f('Region','select',regions,true),f('Date','date',undefined,true),f('PreSales Name','text',undefined,true),f('Training Name','text',undefined,true),f('OEM'),f('Technology Vertical'),f('Certification Done','select',['Yes','No','Ongoing','NA'])]},
{id:'training-conducted',label:'Training Conducted',description:'Record internal or customer enablement sessions.',status:true,fields:[f('Region','select',regions,true),f('Date','date',undefined,true),f('PreSales Name','text',undefined,true),f('Training Name','text',undefined,true),f('OEM'),f('Technology Vertical'),f('Certification')]},
{id:'poc',label:'PoC Tracker',description:'Track proof-of-concept ownership and progress.',status:true,fields:[f('Region','select',regions,true),f('Date','date',undefined,true),f('Presales','text',undefined,true),f('Client Manager'),f('Customer','text',undefined,true),f('PoC Details','textarea',undefined,true),f('OEM'),f('Expected Completion Date','date'),f('Month','select',months),...['Week 1','Week 2','Week 3','Week 4'].map(x=>f(x,'textarea'))]},
{id:'customer-workshop',label:'Customer Workshop',description:'Document workshops delivered to customers.',status:true,fields:[f('Region','select',regions,true),f('Date','date',undefined,true),f('Presales','text',undefined,true),f('Client Manager'),f('Customer','text',undefined,true),f('Workshop Details','textarea',undefined,true),f('OEM'),f('Month','select',months)]},
{id:'win-lost',label:'Win / Lost',description:'Capture closed deal outcomes and value.',fields:[f('PO Date','date',undefined,true),f('Region','select',regions,true),f('Presales','text',undefined,true),f('Account Name','text',undefined,true),f('Win/Lost','select',['Win','Lost'],true),f('Deal Value','number'),f('Remark','textarea')]}
];
export const navExtra=[{id:'targets',label:'Client Manager Targets'},{id:'guide',label:'Column Guide'}];
export {months};
